sudo: true
language: perl
perl:
   - '5.10'
   - '5.14'
   - '5.18'
   - '5.20'
   - '5.22'
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - sudo apt-get update -qq
   - sudo apt-get install -y graphviz
install:
   - cpanm GraphViz2
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
